# Generated by Django 5.0.6 on 2024-05-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificate_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
