# Generated by Django 5.0.6 on 2024-05-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_certificate_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='certificate_url',
            field=models.CharField(max_length=1000),
        ),
    ]
