# Generated by Django 5.0.6 on 2024-05-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_certificate_url'),
        ('store', '0005_user'),
    ]

    operations = [
    ]
