# Generated by Django 5.0.6 on 2024-05-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_merge_0005_alter_product_certificate_url_0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='product',
            name='certificate_url',
        ),
        migrations.AddField(
            model_name='product',
            name='certificate',
            field=models.FilePathField(default='', path='store/static/docs'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/static/img/'),
        ),
    ]
