# Generated by Django 5.0.6 on 2024-05-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_user_remove_product_certificate_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='certificate',
            field=models.URLField(default=''),
        ),
    ]
