# Generated by Django 5.0.6 on 2024-05-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_certificate_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='certificate_url',
            new_name='certificate',
        ),
    ]
