# Generated by Django 5.0.6 on 2024-05-15 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_certificate_url_product_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='certificate',
        ),
        migrations.CreateModel(
            name='ProductDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='store/static/docs')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='store.product')),
            ],
        ),
    ]
