# Generated by Django 5.0.6 on 2024-05-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_certificate_productdocs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDocs',
            new_name='ProductDoc',
        ),
    ]
