# Generated by Django 5.0.6 on 2024-05-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdoc',
            name='file',
            field=models.FileField(upload_to='store/static/store/docs'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/static/store/img/'),
        ),
    ]
