# Generated by Django 4.2.13 on 2024-05-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_userrole_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='username',
        ),
    ]
