# Generated by Django 4.2.13 on 2024-05-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='power_level',
            field=models.IntegerField(default=2),
        ),
    ]
